build:
  image: node:5.0.0
  commands:
    - apt-get -qq update
    - apt-get -qq install sqlite3
    - sqlite3 -init test/data.sql /drone/test.db
    - npm install
    - npm run test
  environment:
    - DRONE_SERVER=http://127.0.0.1:8000
    - DRONE_TOKEN=xxxxxxxx

compose:
  drone:
    pull: true
    image: drone/drone:0.4
    environment:
      - REMOTE_DRIVER=github
      - REMOTE_CONFIG=https://github.com
      - DATABASE_DRIVER=sqlite3
      - DATABASE_CONFIG=/drone/test.db

publish:
  npm:
    username: $$NPM_USERNAME
    password: $$NPM_PASSWORD
    email: $$NPM_EMAIL
    when:
      event: tag
